### ISSUE TITLE
GDB MemoryError : Cannot access memory at address ...

### ISSUE THREAD

**Issue by skanderturki** [ripopov/gdb_systemc_trace#4]
Hi, 
I just tried to use this tool, I am on ubuntu, using SystemC 2.3.3, GNU GDB 9.2, but I get the following error:

```
** ALERT ** ID: initialize Architectural Registers
** ALERT ** BIOS: initialize BIOS
** ALERT ** DCU: initialize Data Cache

Breakpoint 2, sc_core::sc_simcontext::prepare_to_simulate (this=0x555555618510)
    at /media/skander/data/systemc-2.3.3/src/sysc/kernel/sc_simcontext.cpp:678
678 {
Traceback (most recent call last):
  File "/media/skander/data/gdb_systemc_trace/gdb_scripts/run_trace.py", line 58, in <module>
    design = sc_design.SCModule(simctx)
  File "/media/skander/data/gdb_systemc_trace/gdb_scripts/sc_design.py", line 59, in __init__
    self.__init_from_simctx()
  File "/media/skander/data/gdb_systemc_trace/gdb_scripts/sc_design.py", line 66, in __init_from_simctx
    m_child_objects = stdlib_hacks.StdVectorView(self.value['m_child_objects'])
  File "/media/skander/data/gdb_systemc_trace/gdb_scripts/stdlib_hacks.py", line 42, in __init__
    self.size = self.end - self.begin
**gdb.MemoryError: Cannot access memory at address 0x98**
```

Do you have any ideas?
Thanks in advance

**Comment by ripopov** [comment]
>Cannot access memory at address 0x98**

Address 0x98 looks invalid. Can be gdb issue, or some memory corruption within application.

It won't be possible to debug this without reproducer. And unfortunately I no longer use SystemC myself, so I can't spend time on debug.

**Comment by laoshaw** [comment]
same problem here, gdb is good, systemc code runs well otherwise. sigh.

for me the pretty printer does not work and I had to disable that to keep going, then got hit by the same error.
